/* 
 Generated By GameBoyPngConverter

 Tiles map

 TileMap Size      : 20 x 18
*/
#ifndef _SPLASH_LOGO_MAP_H
#define _SPLASH_LOGO_MAP_H

extern unsigned char splash_logo_palette_map[];
extern unsigned char splash_logo_map[];

void init_splash_logo_map();
void update_splash_logo();
void splash_logo_input(unsigned int);

#endif