/* 
 Generated By GameBoyPngConverter

 Tiles data

 Number of Tiles   : 93
*/
#ifndef _SPLASH_LOGO_H
#define _SPLASH_LOGO_H

extern unsigned char splash_logo_palette[];

extern unsigned char splash_logo_data_palette_map[];
extern unsigned char splash_logo_data[];

#endif